In [4]:
import pandas as pd
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing

In [55]:
data=pd.read_csv(r'C:\Users\kowsar\PycharmProjects\PycharmProjects\pythonProject\venv\Scripts\heart.csv')

In [56]:
h=data.head()
h

HeartDiseaseorAttack  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0                     0       1         1          1   40       1       0   
1                     0       0         0          0   25       1       0   
2                     0       1         1          1   28       0       0   
3                     0       1         0          1   27       0       0   
4                     0       1         1          1   24       0       0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0         0             0       0  ...              1            0        5   
1         0             1       0  ...              0            1        3   
2         0             0       1  ...              1            1        5   
3         0             1       1  ...              1            0        2   
4         0             1       1  ...              1            0        2   

   MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  Income  
0        18        15         1    0    9          4       3  
1         0         0         0    0    7          6       1  
2        30        30         1    0    9          4       8  
3         0         0         0    0   11          3       6  
4         3         0         0    0   11          5       4  

[5 rows x 22 columns]

In [57]:
data.size

5580960

In [58]:
#checking are there any missing data
m_d=data.isnull().sum()
m_d

HeartDiseaseorAttack    0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
Diabetes                0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [82]:
x=np.asarray(data[['Age', 'Sex', 'HighBP', 'HighChol', 'BMI', 'Smoker', 'Stroke', 'Diabetes', 'PhysActivity', 'Fruits', 'MentHlth', 'PhysHlth', 'DiffWalk', 'Income', 'Education', 'AnyHealthcare', 'NoDocbcCost']])
x[0:5]

array([[ 9,  0,  1,  1, 40,  1,  0,  0,  0,  0, 18, 15,  1,  3,  4,  1,
         0],
       [ 7,  0,  0,  0, 25,  1,  0,  0,  1,  0,  0,  0,  0,  1,  6,  0,
         1],
       [ 9,  0,  1,  1, 28,  0,  0,  0,  0,  1, 30, 30,  1,  8,  4,  1,
         1],
       [11,  0,  1,  0, 27,  0,  0,  0,  1,  1,  0,  0,  0,  6,  3,  1,
         0],
       [11,  0,  1,  1, 24,  0,  0,  0,  1,  1,  3,  0,  0,  4,  5,  1,
         0]], dtype=int64)

In [83]:
y=np.asarray(data['HeartDiseaseorAttack'])
y[0:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [84]:
#Normalizing 
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()
scaler.fit(x).transform(x)

array([[ 0.31690008, -0.88702088,  1.15368814, ..., -1.06559465,
         0.22686264, -0.30317313],
       [-0.33793279, -0.88702088, -0.86678537, ...,  0.96327159,
        -4.40795367,  3.29844532],
       [ 0.31690008, -0.88702088,  1.15368814, ..., -1.06559465,
         0.22686264,  3.29844532],
       ...,
       [-1.97501498, -0.88702088, -0.86678537, ..., -0.05116153,
         0.22686264, -0.30317313],
       [-0.33793279,  1.12736918,  1.15368814, ..., -0.05116153,
         0.22686264, -0.30317313],
       [ 0.31690008, -0.88702088,  1.15368814, ...,  0.96327159,
         0.22686264, -0.30317313]])

In [85]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=4)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(202944, 17) (202944,)
(50736, 17) (50736,)


In [86]:
#train
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR=LogisticRegression(C=0.01, solver='liblinear').fit(x_train, y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [87]:
#test
yhat=LR.predict(x_test)
print(yhat[0:50])
print(y_test[0:50])

[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 1 0]


In [88]:
yhat_prob=LR.predict_proba(x_test)
yhat_prob[0:20]

array([[0.875378  , 0.124622  ],
       [0.92389476, 0.07610524],
       [0.91519587, 0.08480413],
       [0.98070652, 0.01929348],
       [0.88597498, 0.11402502],
       [0.91194203, 0.08805797],
       [0.88615406, 0.11384594],
       [0.95945226, 0.04054774],
       [0.95864021, 0.04135979],
       [0.8985034 , 0.1014966 ],
       [0.99194424, 0.00805576],
       [0.9953357 , 0.0046643 ],
       [0.4776752 , 0.5223248 ],
       [0.67991904, 0.32008096],
       [0.97025022, 0.02974978],
       [0.89465746, 0.10534254],
       [0.99272909, 0.00727091],
       [0.80922213, 0.19077787],
       [0.92322262, 0.07677738],
       [0.97209495, 0.02790505]])

In [89]:
#Evaluation
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat, pos_label=0)

0.9052080846661892

In [90]:
from sklearn.metrics import classification_report
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.91      0.99      0.95     45891
           1       0.55      0.10      0.16      4845

    accuracy                           0.91     50736
   macro avg       0.73      0.54      0.56     50736
weighted avg       0.88      0.91      0.88     50736

